name: Build and Deploy to Arvan Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js environment (if your project uses Node.js)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21' # نسخه مورد نیاز Node.js را تنظیم کنید

      # Install dependencies
      - name: Install Dependencies
        run: yarn install

      # Build the project
      - name: Build Project
        run: npm run build

      # Upload to Arvan Cloud
      - name: Deploy to Arvan Cloud
        env:
          ARVAN_ACCESS_KEY: ${{ secrets.ARVAN_ACCESS_KEY }} # کلید API آروان
          ARVAN_SECRET_KEY: ${{ secrets.ARVAN_SECRET_KEY }}   # نام باکت آروان
        run: |
          # نصب ابزار s3cmd
          sudo apt update && sudo apt install -y s3cmd

          # تنظیم s3cmd برای ابر آروان
          echo "[default]
          access_key = b8e1cfb1-39f5-49d9-be8c-824f19ed7449
          secret_key = d722aedb7b06bfdf977a9d2eb803c0afdb02be7f65acf6b3ba3ae500eca43651
          host_base = s3.ir-thr-at1.arvanstorage.ir
          host_bucket = %(bucket)s.s3.ir-thr-at1.arvanstorage.ir
          use_https = True
          " > ~/.s3cfg

          # آپلود محتویات پوشه dist به آروان
          # s3cmd sync --acl-public ./dist/assets/ s3://nobat-cdn
